### ISSUE TITLE
Spanish Language Dictionary

### ISSUE THREAD

**Issue by vlasvlasvlas** [pramsey/pgsql-addressing-dictionary#8]
Hi! love this idea.

its ok if i help starting spanish dictionary for latam?

thanks!

**Comment by pramsey** [comment]
Yes, an "es" dictionary would be great.

**Comment by vlasvlasvlas** [comment]
done! :)

**Comment by pramsey** [comment]
Great! Fire it into a PR

**Comment by vlasvlasvlas** [comment]
done. Thanks!
